version: '2'

services:
  nuxt:
    extends:
      file: docker-compose.yml
      service: nuxt
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - /usr/src/app
  db:
    extends:
      file: docker-compose.yml
      service: db

volumes:
  db_data:
    driver: local