version: '2'

services:
  nuxt:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    links:
      - db
    environment:
      HOST: 0.0.0.0

  db:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local